name: CI

on:
  pull_request:
    branches: [main]

jobs:
  deploy_blog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.18.0
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "latest/*"
          cache: "pnpm"
      - name: install dependencies
        run: pnpm install
      - name: build
        run: pnpm build
      - name: deploy github pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
